<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Runtime\Runtime.csproj" />
    <ProjectReference Include="..\Storage.FileSystem\Storage.FileSystem.csproj" />
  </ItemGroup>

</Project>
